### ISSUE TITLE
Replacing subsectors

### ISSUE THREAD

**Issue by felskia** [map-yemen/map-yemen.github.io#17]
We'll just need to change out the subsectors to these: 

o   Agriculture
o   Water
o   Trade and employment
o   Health
o   Nutrition
o   Education

@DylanMoriarty let me know if you can do this or if we need to get Marc in.

**Comment by DylanMoriarty** [comment]
To be clear are you requesting we swap out these dropdown values with those?

<img width="859" alt="screenshot 2017-03-13 21 46 39" src="https://cloud.githubusercontent.com/assets/9341928/23882385/a0ab974a-0836-11e7-8095-a81217ba8cc4.png">

If so do we have the arabic text for that too? I'll confirm with Marc if just swapping out the strings will be sufficient here.

**Comment by felskia** [comment]
Yes, those are it. Getting the translations for them as well from Hagar now.

**Comment by felskia** [comment]
Here you are @DylanMoriarty:

o   Agriculture - الزراعة
o   Water - المياه
o   Trade and employment – التجارة و التوظيف
o   Health - الصحة
o   Nutrition - التغذية
o   Education - التعليم

**Comment by DylanMoriarty** [comment]
Grabbed in this PR: https://github.com/map-yemen/admin/pull/2
