### ISSUE TITLE
Zoom in one more level - all maps of Yemen

### ISSUE THREAD

**Issue by felskia** [map-yemen/map-yemen.github.io#20]
Right now if you press the + button once it is the perfect size, the one the client wants. Can we start all the same maps at this level?

**Comment by DylanMoriarty** [comment]
~~@felskia Can you clarify if you're asking it to start one zoom level further down, or if you're asking for me to allow the user to zoom down one more level than is currently allowed?~~

Ah, re-reading I'm pretty sure it's the former. Will do.
