### ISSUE TITLE
Yemen Logo

### ISSUE THREAD

**Issue by DylanMoriarty** [map-yemen/map-yemen.github.io#3]
Need to replace the MapEgypt logo with MapYemen.

@felskia I recall from prior discussions we were relying on them to give us an updated version of the logo with 'Yemen' instead of Egypt.

If you shoot over the original file and note the font I can grab that as well.

**Comment by felskia** [comment]
@DylanMoriarty here is the logo. Let me know if this works. Just set the Yemen link to Hagar so the more we can get done before she sees it in the morning the better. 

Thanks!
![egypt-logo](https://cloud.githubusercontent.com/assets/5421566/23729959/d1a1fdce-0432-11e7-85f9-8e4a293ce644.png)

**Comment by DylanMoriarty** [comment]
@felskia I'm a bit confused by this- are we not going with MAP Yemen as a logo for this site?

**Comment by DylanMoriarty** [comment]
<img width="523" alt="screenshot 2017-03-08 23 18 06" src="https://cloud.githubusercontent.com/assets/9341928/23735745/8355f4d6-0455-11e7-9218-924066611286.png">

I've merged in a PR with a MAP-Yemen logo (edited from the dropox file) for now. If you wanted the logo to be MAP-Egypt for this, I've opened a PR to revert it back.
