### ISSUE TITLE
Uncaught Error: Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by sethvincent** [map-yemen/map-yemen.github.io#32]
Currently seeing this error locally and at map-yemen.github.io (though its message is truncated there)

```
invariant.js:42 Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. 
Youmight be adding a ref to a component that was not created inside a component's `render` 
method, or you have multiple copies of React loaded 
```

This can happen if there's a ref to a component that was not created inside a component's `render` method.

Or if there are multiple copies of React loaded.

More info here: https://fb.me/react-refs-must-have-owner

It doesn't seem like there are multiple copies of React.

I haven't found any instances of refs being created outside a render function, either, though.

**Comment by dereklieu** [comment]
This was a dependency issue. I think one of the `react-` libraries was loading another version.
