### ISSUE TITLE
Scripts don't function in Chrome

### ISSUE THREAD

**Issue by DylanMoriarty** [map-yemen/map-yemen.github.io#5]
Works in Firefox though, curiously enough.

Saw this running the site locally too. CORS issue?

**Comment by mapmeld** [comment]
I wonder if it could be a caching issue..? Works locally or when I do Chrome incognito

**Comment by DylanMoriarty** [comment]
Yeah, incognito works fine for me too.

The original Map-Egypt site seems to work fine in Chrome. Any idea what the difference may be caused by?

**Comment by DylanMoriarty** [comment]
Clearing the cache went ahead and fixed it. Yay!
